name: Unit Tests

on:
  push:
    branches:
    # long-lived branches
    - master

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: ${{ matrix.env }} yarn test
      env:
        CI: true
